# Generated by Django 4.2.6 on 2023-10-20 16:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePageModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('bio', models.TextField(blank=True, max_length=512, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('profile_picture', models.ImageField(blank='True', default='uploads/userprofile/profile_pictures/default.png', upload_to='uploads/userprofile/profile_pictures')),
                ('cover_picture', models.ImageField(blank='True', default='uploads/userprofile/cover_pictures/default.png', upload_to='uploads/userprofile/cover_pictures')),
            ],
        ),
    ]
